import {
  Department,
  Profile,
  Organization,
  Category,
  EmissionFactor,
  CarbonTransaction,
  EnvironmentalGoal,
  CSRActivity,
  EmployeeParticipation,
  Challenge,
  ChallengeParticipation,
  Badge,
  BadgeAward,
  Reward,
  RewardRedemption,
  DepartmentScore,
  Notification,
  XPTransaction,
  ComplianceIssue,
  ESGPolicy,
  Audit,
  PolicyAcknowledgement,
  SupplierRecord,
  MaterialityTopic,
} from '@/types'

// ─── Default Organizations ────────────────────────────────────
export const defaultOrganization: Organization = {
  id: 'org-greentech-123',
  name: 'GreenTech Manufacturing Pvt. Ltd.',
  logo_url: null,
  env_weight: 40,
  social_weight: 30,
  gov_weight: 30,
  auto_emission_calc: true,
  evidence_required: false,
  badge_auto_award: true,
  notify_in_app: true,
  notify_email: false,
  notify_email_admin: 'admin@greentech.demo',
  policy_reminder_days: 3,
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
}

// ─── Default Departments ──────────────────────────────────────
export const defaultDepartments: Department[] = [
  {
    id: 'dept-mfg',
    org_id: 'org-greentech-123',
    name: 'Manufacturing & Operations',
    code: 'MFG',
    parent_id: null,
    head_id: 'user-mfg-head',
    employee_count: 45,
    status: 'active',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dept-logistics',
    org_id: 'org-greentech-123',
    name: 'Logistics & Supply Chain',
    code: 'LOG',
    parent_id: null,
    head_id: 'user-log-head',
    employee_count: 22,
    status: 'active',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dept-hr',
    org_id: 'org-greentech-123',
    name: 'Human Resources',
    code: 'HR',
    parent_id: null,
    head_id: 'user-hr-head',
    employee_count: 8,
    status: 'active',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'dept-rnd',
    org_id: 'org-greentech-123',
    name: 'Research & Development',
    code: 'RND',
    parent_id: null,
    head_id: 'user-rnd-head',
    employee_count: 15,
    status: 'active',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// ─── Default Categories ───────────────────────────────────────
export const defaultCategories: Category[] = [
  { id: 'cat-csr-env', org_id: 'org-greentech-123', name: 'Reforestation & Planting', type: 'csr_activity', status: 'active' },
  { id: 'cat-csr-social', org_id: 'org-greentech-123', name: 'Community Care', type: 'csr_activity', status: 'active' },
  { id: 'cat-chal-energy', org_id: 'org-greentech-123', name: 'Energy Conservation', type: 'challenge', status: 'active' },
  { id: 'cat-chal-waste', org_id: 'org-greentech-123', name: 'Waste Reduction', type: 'challenge', status: 'active' },
]

// ─── Default Profiles/Users ───────────────────────────────────
export const defaultProfiles: Profile[] = [
  {
    id: 'user-admin',
    email: 'admin@greentech.demo',
    full_name: 'Amit Sharma',
    role: 'admin',
    department_id: null,
    total_xp: 0,
    total_points: 0,
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-ceo',
    email: 'ceo@greentech.demo',
    full_name: 'Rajesh Nair',
    role: 'executive',
    department_id: null,
    total_xp: 150,
    total_points: 150,
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-esg',
    email: 'esg@greentech.demo',
    full_name: 'Priya Patel',
    role: 'esg_manager',
    department_id: null,
    total_xp: 450,
    total_points: 450,
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-mfg-head',
    email: 'mfg-head@greentech.demo',
    full_name: 'Sanjay Deshmukh',
    role: 'dept_head',
    department_id: 'dept-mfg',
    total_xp: 800,
    total_points: 800,
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-employee-1',
    email: 'employee1@greentech.demo',
    full_name: 'Arjun Verma',
    role: 'employee',
    department_id: 'dept-mfg',
    total_xp: 1250,
    total_points: 750,
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-employee-2',
    email: 'employee2@greentech.demo',
    full_name: 'Neha Sen',
    role: 'employee',
    department_id: 'dept-logistics',
    total_xp: 950,
    total_points: 950,
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// ─── Default Emission Factors ──────────────────────────────────
export const defaultEmissionFactors: EmissionFactor[] = [
  {
    id: 'ef-electricity-grid',
    org_id: 'org-greentech-123',
    name: 'Indian Grid Electricity Mix',
    activity_type: 'manufacturing',
    factor_value: 0.82,
    unit: 'kg CO₂e / kWh',
    source: 'CEA CO2 Baseline Database 2023',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ef-diesel-generator',
    org_id: 'org-greentech-123',
    name: 'Industrial Diesel Combustion',
    activity_type: 'manufacturing',
    factor_value: 2.68,
    unit: 'kg CO₂e / litre',
    source: 'IPCC Guidelines 2006',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ef-truck-freight',
    org_id: 'org-greentech-123',
    name: 'Heavy Duty Freight Truck (Diesel)',
    activity_type: 'fleet',
    factor_value: 0.15,
    unit: 'kg CO₂e / t-km',
    source: 'DEFRA Carbon Factors 2023',
    created_at: new Date().toISOString(),
  },
]

// ─── Default Environmental Goals ──────────────────────────────
export const defaultGoals: EnvironmentalGoal[] = [
  {
    id: 'goal-reduce-carbon',
    org_id: 'org-greentech-123',
    department_id: null,
    title: 'Reduce Org Carbon Footprint',
    description: 'Reduce company-wide carbon emissions by 15% YTD.',
    target_value: 50000,
    current_value: 38200,
    unit: 'kg CO₂e',
    start_date: '2026-01-01',
    deadline: '2026-12-31',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'goal-mfg-efficiency',
    org_id: 'org-greentech-123',
    department_id: 'dept-mfg',
    title: 'Improve Plant Energy Efficiency',
    description: 'Target plant emission reduction via solar and optimization.',
    target_value: 20000,
    current_value: 23500, // Trigger trajectory warning (>20% off target)
    unit: 'kg CO₂e',
    start_date: '2026-01-01',
    deadline: '2026-08-31',
    status: 'active',
    created_at: new Date().toISOString(),
  },
]

// ─── Default Carbon Transactions ────────────────────────────────
export const defaultCarbonTransactions: CarbonTransaction[] = [
  {
    id: 'tx-1',
    org_id: 'org-greentech-123',
    department_id: 'dept-mfg',
    emission_factor_id: 'ef-electricity-grid',
    quantity: 12000,
    calculated_emission_kg: 9840,
    auto_calculated: true,
    source_type: 'manufacturing',
    date: '2026-06-15',
    notes: 'Monthly assembly line energy consumption log',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tx-2',
    org_id: 'org-greentech-123',
    department_id: 'dept-logistics',
    emission_factor_id: 'ef-truck-freight',
    quantity: 25000,
    calculated_emission_kg: 3750,
    auto_calculated: true,
    source_type: 'fleet',
    date: '2026-06-20',
    notes: 'Outbound product supply cargo shipments',
    created_at: new Date().toISOString(),
  },
  // Historical data spread across last 6 months for heatmap visibility
  { id: 'tx-3', org_id: 'org-greentech-123', department_id: 'dept-mfg', emission_factor_id: 'ef-electricity-grid', quantity: 10800, calculated_emission_kg: 8856, auto_calculated: true, source_type: 'manufacturing', date: '2026-05-10', notes: 'May assembly line energy', created_at: new Date().toISOString() },
  { id: 'tx-4', org_id: 'org-greentech-123', department_id: 'dept-logistics', emission_factor_id: 'ef-truck-freight', quantity: 22000, calculated_emission_kg: 3300, auto_calculated: true, source_type: 'fleet', date: '2026-05-18', notes: 'May freight runs', created_at: new Date().toISOString() },
  { id: 'tx-5', org_id: 'org-greentech-123', department_id: 'dept-mfg', emission_factor_id: 'ef-electricity-grid', quantity: 11500, calculated_emission_kg: 9430, auto_calculated: true, source_type: 'manufacturing', date: '2026-04-12', notes: 'April production run', created_at: new Date().toISOString() },
  { id: 'tx-6', org_id: 'org-greentech-123', department_id: 'dept-hr', emission_factor_id: 'ef-electricity-grid', quantity: 2500, calculated_emission_kg: 2050, auto_calculated: true, source_type: 'other', date: '2026-04-20', notes: 'Office energy April', created_at: new Date().toISOString() },
  { id: 'tx-7', org_id: 'org-greentech-123', department_id: 'dept-mfg', emission_factor_id: 'ef-electricity-grid', quantity: 13200, calculated_emission_kg: 10824, auto_calculated: true, source_type: 'manufacturing', date: '2026-03-08', notes: 'March high-demand production', created_at: new Date().toISOString() },
  { id: 'tx-8', org_id: 'org-greentech-123', department_id: 'dept-logistics', emission_factor_id: 'ef-truck-freight', quantity: 28000, calculated_emission_kg: 4200, auto_calculated: true, source_type: 'fleet', date: '2026-03-22', notes: 'March distribution runs', created_at: new Date().toISOString() },
  { id: 'tx-9', org_id: 'org-greentech-123', department_id: 'dept-mfg', emission_factor_id: 'ef-electricity-grid', quantity: 9500, calculated_emission_kg: 7790, auto_calculated: true, source_type: 'manufacturing', date: '2026-02-14', notes: 'Feb manufacturing energy', created_at: new Date().toISOString() },
  { id: 'tx-10', org_id: 'org-greentech-123', department_id: 'dept-hr', emission_factor_id: 'ef-electricity-grid', quantity: 2100, calculated_emission_kg: 1722, auto_calculated: true, source_type: 'other', date: '2026-02-25', notes: 'Office Feb energy', created_at: new Date().toISOString() },
  { id: 'tx-11', org_id: 'org-greentech-123', department_id: 'dept-mfg', emission_factor_id: 'ef-electricity-grid', quantity: 14000, calculated_emission_kg: 11480, auto_calculated: true, source_type: 'manufacturing', date: '2026-07-05', notes: 'July production ramp-up', created_at: new Date().toISOString() },
  { id: 'tx-12', org_id: 'org-greentech-123', department_id: 'dept-logistics', emission_factor_id: 'ef-truck-freight', quantity: 30000, calculated_emission_kg: 4500, auto_calculated: true, source_type: 'fleet', date: '2026-07-15', notes: 'July logistics expansion', created_at: new Date().toISOString() },
]

// ─── Default CSR Activities ───────────────────────────────────
export const defaultCSRActivities: CSRActivity[] = [
  {
    id: 'csr-1',
    org_id: 'org-greentech-123',
    title: 'EcoDrive Reforestation Campaign',
    category_id: 'cat-csr-env',
    date: '2026-07-25',
    points_reward: 200,
    description: 'Planting 500 saplings in the local forest reserve. Transport and refreshments provided.',
    max_participants: 30,
    department_id: null,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'csr-2',
    org_id: 'org-greentech-123',
    title: 'Primary School Solar STEM Setup',
    category_id: 'cat-csr-social',
    date: '2026-08-10',
    points_reward: 350,
    description: 'Volunteering to install mini solar arrays and teach renewable science to community children.',
    max_participants: 10,
    department_id: null,
    status: 'active',
    created_at: new Date().toISOString(),
  },
]

// ─── Default Challenges ───────────────────────────────────────
export const defaultChallenges: Challenge[] = [
  {
    id: 'chal-1',
    org_id: 'org-greentech-123',
    title: 'Zero Waste Week',
    description: 'Complete one week without single-use plastics or paper packaging. Submit photos of your eco-friendly containers.',
    category_id: 'cat-chal-waste',
    xp_reward: 300,
    difficulty: 'medium',
    evidence_required: true,
    deadline: '2026-07-20',
    department_id: null,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'chal-2',
    org_id: 'org-greentech-123',
    title: 'Commute Green Challenge',
    description: 'Walk, cycle, or carpool to work for 5 consecutive days. Upload transport logs.',
    category_id: 'cat-chal-energy',
    xp_reward: 450,
    difficulty: 'hard',
    evidence_required: true,
    deadline: '2026-07-30',
    department_id: null,
    status: 'active',
    created_at: new Date().toISOString(),
  },
]

// ─── Default Rewards ──────────────────────────────────────────
export const defaultRewards: Reward[] = [
  {
    id: 'rew-cup',
    org_id: 'org-greentech-123',
    name: 'EcoSphere Thermal Flask',
    description: 'Double-walled stainless steel thermal flask with premium wood grain lid.',
    points_required: 400,
    stock: 12,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rew-gift',
    org_id: 'org-greentech-123',
    name: '₹500 Organic Grocer Voucher',
    description: 'Gift card redeemable at local organic co-operatives and green stores.',
    points_required: 600,
    stock: 25,
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rew-tree',
    org_id: 'org-greentech-123',
    name: 'Plant a Dedicated Tree',
    description: 'Plant a fruit-bearing tree named after you with regular coordinates and photos.',
    points_required: 200,
    stock: 99,
    status: 'active',
    created_at: new Date().toISOString(),
  },
]

// ─── Default Badges ───────────────────────────────────────────
export const defaultBadges: Badge[] = [
  {
    id: 'badge-novice',
    org_id: 'org-greentech-123',
    name: 'Eco Initiate',
    description: 'Earned when you register and complete your first challenge.',
    icon: '🌱',
    unlock_rule_type: 'challenges_completed',
    unlock_rule_value: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'badge-champion',
    org_id: 'org-greentech-123',
    name: 'Carbon Slayer',
    description: 'Unlock by completing 5 sustainability challenges.',
    icon: '⚔️',
    unlock_rule_type: 'challenges_completed',
    unlock_rule_value: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'badge-xp-1000',
    org_id: 'org-greentech-123',
    name: 'Green Pioneer',
    description: 'Accumulate 1000 total XP points.',
    icon: '✨',
    unlock_rule_type: 'xp_threshold',
    unlock_rule_value: 1000,
    created_at: new Date().toISOString(),
  },
]

// ─── Default Compliance Issues ────────────────────────────────
export const defaultComplianceIssues: ComplianceIssue[] = [
  {
    id: 'issue-1',
    org_id: 'org-greentech-123',
    title: 'Water Discharge pH Inconsistency',
    description: 'Secondary outflow tank registered a pH deviation of 8.9 (Limit is 6.5-8.5). Needs sensor review.',
    severity: 'critical',
    status: 'open',
    owner_id: 'user-mfg-head',
    due_date: '2026-07-10', // Overdue
    department_id: 'dept-mfg',
    audit_id: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'issue-2',
    org_id: 'org-greentech-123',
    title: 'Forklift Fuel Emissions Exceeded Limit',
    description: 'Logistics forklift #04 carbon output exceeds local workshop standard by 12%. Service scheduled.',
    severity: 'high',
    status: 'in_progress',
    owner_id: 'user-employee-2',
    due_date: '2026-07-20',
    department_id: 'dept-logistics',
    audit_id: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// ─── Default ESG Policies ─────────────────────────────────────
export const defaultPolicies: ESGPolicy[] = [
  {
    id: 'pol-1',
    org_id: 'org-greentech-123',
    title: 'Sustainable Resource Procurement Policy',
    description: 'Mandatory guidelines for vendor green compliance scoring.',
    category: 'environmental',
    version: '2.1',
    effective_date: '2026-01-15',
    review_date: '2027-01-15',
    status: 'active',
    document_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pol-2',
    org_id: 'org-greentech-123',
    title: 'Supplier Anti-Bribery & Ethics Policy',
    description: 'Code of conduct and governance protocols for external distributors.',
    category: 'governance',
    version: '1.0',
    effective_date: '2026-03-01',
    review_date: '2027-03-01',
    status: 'active',
    document_url: null,
    created_at: new Date().toISOString(),
  },
]

// ─── Default Audits ───────────────────────────────────────────
export const defaultAudits: Audit[] = [
  {
    id: 'aud-1',
    org_id: 'org-greentech-123',
    title: 'Q2 Industrial Effluent Audit',
    department_id: 'dept-mfg',
    auditor_id: 'user-esg',
    scope: 'Testing chemical output and waste pipeline integrity in central plant.',
    scheduled_date: '2026-06-25',
    findings: 'Found pH levels elevated in Outflow Pipe 3. Created Compliance Issue #1.',
    status: 'completed',
    created_at: new Date().toISOString(),
  },
]

// ─── Default XP Transactions ──────────────────────────────────
export const defaultXPTransactions: XPTransaction[] = [
  {
    id: 'tx-esg-1',
    employee_id: 'user-esg',
    amount: 150,
    source_type: 'manual',
    source_id: null,
    description: 'System Onboarding Welcome Bonus Points',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-esg-2',
    employee_id: 'user-esg',
    amount: 200,
    source_type: 'challenge',
    source_id: 'chal-1',
    description: 'Completed Green Office Energy efficiency audit',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-esg-3',
    employee_id: 'user-esg',
    amount: 100,
    source_type: 'manual',
    source_id: null,
    description: 'ESG Academy Awareness Starter Module',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-ceo-1',
    employee_id: 'user-ceo',
    amount: 150,
    source_type: 'manual',
    source_id: null,
    description: 'System Onboarding Welcome Bonus Points',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-mfg-1',
    employee_id: 'user-mfg-head',
    amount: 150,
    source_type: 'manual',
    source_id: null,
    description: 'System Onboarding Welcome Bonus Points',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-mfg-2',
    employee_id: 'user-mfg-head',
    amount: 400,
    source_type: 'challenge',
    source_id: 'chal-2',
    description: 'Corporate Carbon Footprint Audit Campaign',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-mfg-3',
    employee_id: 'user-mfg-head',
    amount: 250,
    source_type: 'csr_activity',
    source_id: 'csr-1',
    description: 'Waste Minimization Scheme Initiative Lead',
    org_id: 'org-greentech-123',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const defaultSuppliers: SupplierRecord[] = [
  {
    id: 'sup_001',
    name: 'Sunrise Steel Pvt. Ltd.',
    category: 'Raw Materials',
    country: 'India',
    envScore: 62,
    socialScore: 74,
    govScore: 68,
    overallScore: 67,
    riskLevel: 'medium',
    lastAudit: '2026-04-10',
    certifications: ['ISO 14001'],
  },
  {
    id: 'sup_002',
    name: 'GreenPath Logistics',
    category: 'Logistics',
    country: 'Germany',
    envScore: 88,
    socialScore: 82,
    govScore: 90,
    overallScore: 87,
    riskLevel: 'low',
    lastAudit: '2026-05-22',
    certifications: ['ISO 14001', 'SA8000', 'EcoVadis Gold'],
  },
  {
    id: 'sup_003',
    name: 'ChemCore Industries',
    category: 'Raw Materials',
    country: 'China',
    envScore: 38,
    socialScore: 45,
    govScore: 50,
    overallScore: 43,
    riskLevel: 'high',
    lastAudit: '2025-11-05',
    certifications: [],
  },
  {
    id: 'sup_004',
    name: 'SolarPower Solutions',
    category: 'Energy',
    country: 'India',
    envScore: 95,
    socialScore: 80,
    govScore: 85,
    overallScore: 88,
    riskLevel: 'low',
    lastAudit: '2026-06-01',
    certifications: ['B Corp', 'ISO 50001'],
  },
  {
    id: 'sup_005',
    name: 'PackRight Ltd.',
    category: 'Packaging',
    country: 'UK',
    envScore: 72,
    socialScore: 68,
    govScore: 75,
    overallScore: 72,
    riskLevel: 'low',
    lastAudit: '2026-03-18',
    certifications: ['FSC Certified'],
  },
]

export const defaultMaterialityTopics: MaterialityTopic[] = [
  { id: 'mt_1', name: 'GHG Emissions & Climate Change', category: 'environmental', stakeholderImpact: 5, businessImpact: 5, description: 'Direct priority given the EU CBAM regulations and national emission compliance guidelines.' },
  { id: 'mt_2', name: 'Workforce Diversity & inclusion', category: 'social', stakeholderImpact: 4, businessImpact: 3, description: 'Critical for company reputation and social license to operate.' },
  { id: 'mt_3', name: 'Cybersecurity & Data Privacy', category: 'governance', stakeholderImpact: 5, businessImpact: 4, description: 'Essential protection required to secure corporate IP and prevent regulatory penalties.' },
  { id: 'mt_4', name: 'Circular Economy & Resource Waste', category: 'environmental', stakeholderImpact: 3, businessImpact: 4, description: 'High business impact to optimize production costs and reduce material wastage.' },
  { id: 'mt_5', name: 'Business Ethics & Anti-Corruption', category: 'governance', stakeholderImpact: 5, businessImpact: 5, description: 'Zero tolerance policy is vital to operate as a listed entity without risk.' },
  { id: 'mt_6', name: 'Community Relations & CSR', category: 'social', stakeholderImpact: 3, businessImpact: 2, description: 'Ongoing local initiatives with moderate business impact but key social value.' }
]


